/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AddressDto
 */
@JsonPropertyOrder({
  AddressDto.JSON_PROPERTY_PREFECTURES,
  AddressDto.JSON_PROPERTY_MUNICIPALITIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-21T13:00:09.908379746Z[UTC]")
public class AddressDto {
  public static final String JSON_PROPERTY_PREFECTURES = "prefectures";
  private String prefectures;

  public static final String JSON_PROPERTY_MUNICIPALITIES = "municipalities";
  private String municipalities;

  public AddressDto() {
  }

  public AddressDto prefectures(String prefectures) {
    
    this.prefectures = prefectures;
    return this;
  }

   /**
   * Get prefectures
   * @return prefectures
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PREFECTURES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPrefectures() {
    return prefectures;
  }


  @JsonProperty(JSON_PROPERTY_PREFECTURES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrefectures(String prefectures) {
    this.prefectures = prefectures;
  }


  public AddressDto municipalities(String municipalities) {
    
    this.municipalities = municipalities;
    return this;
  }

   /**
   * Get municipalities
   * @return municipalities
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MUNICIPALITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMunicipalities() {
    return municipalities;
  }


  @JsonProperty(JSON_PROPERTY_MUNICIPALITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMunicipalities(String municipalities) {
    this.municipalities = municipalities;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressDto addressDto = (AddressDto) o;
    return Objects.equals(this.prefectures, addressDto.prefectures) &&
        Objects.equals(this.municipalities, addressDto.municipalities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prefectures, municipalities);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressDto {\n");
    sb.append("    prefectures: ").append(toIndentedString(prefectures)).append("\n");
    sb.append("    municipalities: ").append(toIndentedString(municipalities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

