/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddressDto
 */
public class AddressDtoTest {
    private final AddressDto model = new AddressDto();

    /**
     * Model tests for AddressDto
     */
    @Test
    public void testAddressDto() {
        // TODO: test AddressDto
    }

    /**
     * Test the property 'prefectures'
     */
    @Test
    public void prefecturesTest() {
        // TODO: test prefectures
    }

    /**
     * Test the property 'municipalities'
     */
    @Test
    public void municipalitiesTest() {
        // TODO: test municipalities
    }

}
